version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      - CIRCLE_COMPARE_URL: https://github.com/sumut/revisited-spring-boot-recipe-app/compare/078791d0c4b83384d908c1835c350f17fbcc1be6...abd707a4ed68836d7d3a4329ab3f8da6d71f6be7
      - MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{‌{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{‌{ checksum "pom.xml" }}
      - run: mvn integration-test cobertura:cobertura
      - store_test_results:
          path: target/surefire-reports
      - run:
          name: Send to CodeCov
          command: bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  workflow:
    jobs:
      - build